name:                hansible-ansible
version:             0.1.0.0
license:             AllRightsReserved
author:              "Jonas Gunz"
maintainer:          "himself@jonasgunz.de"
copyright:           "2022 Jonas Gunz"

c-sources: csrc/*.c
cc-options:
  - '-D_PYINCLUDE=<python3.10/Python.h>'
include-dirs: csrc/
extra-libraries:
  - python3.10
  - git2

dependencies:
- base >= 4.7 && < 5
- network
- async
- unix
- json
- bytestring
- directory
- yesod
- yesod-persistent
- yesod-core
- persistent
- persistent-mysql >= 2.13.1
- monad-logger
- persistent-template
- yesod-form
- lens
- time-compat
- split
- containers
- mtl
- text

extra-deps:
  - Cabal

executables:
  hansible-ansible-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: []
      #    - hansible-ansible
